### ISSUE TITLE
这个插件的实际应用场景是什么

### ISSUE THREAD

**Issue by XWC95** [wangjiegulu/RapidMetaInfPlugin#1]

**Comment by wangjiegulu** [comment]
可以看[我的博客](http://blog.wangjiegulu.com/2018/02/05/Android%E7%AB%AF%E7%94%9F%E6%88%90META-INF%E4%BF%A1%E6%81%AF%E6%96%87%E4%BB%B6%E7%9A%84Gradle%E6%8F%92%E4%BB%B6%20RapidMetaInfPlugin/)
