### ISSUE TITLE
能把广告去了么？谢谢

### ISSUE THREAD

**Issue by MichaelJokAr** [wangjiegulu/RapidMetaInfPlugin#2]
能把广告去了么？谢谢
需要start，flow，我们github上弄，好么

**Comment by wangjiegulu** [comment]
@MichaelJokAr 哪来的广告？有点莫名其妙

**Comment by MichaelJokAr** [comment]
![image](https://user-images.githubusercontent.com/8246218/58524789-f5ac6080-81fb-11e9-8a18-c732da7675f9.png)
z难道这不是你自己的代码？呵呵
